stations:
  Shinomiya:
    lat: 35.66927
    lon: 140.0243
    times:
      - "05:16"
      - "06:02"
      - "06:47"
      - "07:35"
      - "08:10"
      - "09:28"
      - "10:55"
      - "12:03"
      - "13:46"
      - "15:20"
      - "17:05"
      - "18:42"
      - "20:11"
      - "22:08"
      - "24:20"

  Fujiwara:
    lat: 35.67307
    lon: 140.0289
    times:
      - "05:30"
      - "06:18"
      - "07:01"
      - "08:22"
      - "09:05"
      - "10:40"
      - "11:58"
      - "13:12"
      - "14:49"
      - "16:33"
      - "18:00"
      - "19:27"
      - "21:14"
      - "23:06"

  Iino:
    lat: 35.67677
    lon: 140.0334
    times:
      - "05:45"
      - "06:10"
      - "07:26"
      - "08:55"
      - "09:40"
      - "11:08"
      - "12:34"
      - "14:01"
      - "15:47"
      - "17:30"
      - "19:02"
      - "20:36"
      - "22:25"
      - "24:10"
